# See https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md for all rules.
default: true
MD013:
    code_blocks: false
    tables: false
    headings: false
MD029:
    style: ordered
MD030: false
MD033: false
MD041: false
MD046: false
MD049: false
